# Generated by Django 3.1.7 on 2021-04-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='author/<django.db.models.fields.CharField>')),
                ('website', models.URLField()),
                ('telegram', models.URLField()),
                ('github', models.URLField()),
                ('gitlub', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
    ]
