# Generated by Django 3.1.7 on 2021-03-25 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='posts/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
